version: '3'

services:
  postgres:
    image: postgres:14-alpine
    hostname: postgres
    restart: always
    environment:
      - POSTGRES_DB=mushop_user
      - POSTGRES_USER=mushop
      - POSTGRES_PASSWORD=mushop
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        nodeEnv: development
    image: mushop/user
    hostname: user
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: false
    depends_on:
      - postgres
    volumes:
      - ./node_modules/@nestjs:/usr/src/app/node_modules/@nestjs
      - ./src:/usr/src/app/src
    environment:
      - reschedule=on-node-failure
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=mushop_user
      - POSTGRES_USER=mushop
      - POSTGRES_PASSWORD=mushop
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'start:dev']

volumes:
  postgres_data:
