
# PostgreSQL connection settings
POSTGRES_HOST: localhost
POSTGRES_PORT: 5432
POSTGRES_DB: mushop_carts
POSTGRES_USER: mushop
POSTGRES_PASSWORD: mushop

# The name of the table to store the carts in
POSTGRES_CARTS_TABLE: carts

server:
  port: 80
  access-log:
    format: "%h %l %u %t %r %s %b %{Referer}i"
